/**
 * Block reference data — one entry per block in github.com/kawaind/bimota/blocks.
 * This is the single source of "what it does / how it works / when to use it"
 * shown on pages/blocks.html. Kept as data (not scattered HTML) so it's easy
 * to update when a block changes.
 *
 * category values: "layout", "product", "interactive", "site"
 */
window.BLOCK_DATA = [
  {
    id: 'hero',
    name: 'Hero',
    category: 'layout',
    what: 'A full-width banner, almost always the first thing on a page: a background image or video, a heading, optional subheading, and a call-to-action button.',
    how: 'You give it one image (or a video link) and some text. The block stretches the image to fill the width of the screen, overlays your heading/text on top, and adds a pause/play button automatically if you used a video instead of an image.',
    when: 'Use once, at the very top of a page — landing pages, model pages, campaign pages.',
    fields: [
      ['Image or video', 'Background media. A still image, or a link ending in .mp4 for a looping background video.'],
      ['Heading', 'Main title, shown large.'],
      ['Subheading / body text', 'Optional short supporting line.'],
      ['CTA link', 'Optional button, e.g. "Discover Tesi H2".'],
    ],
    snippet: '| Hero |  |\n|---|---|\n| ![Tesi H2 hero image](/media/tesi-h2-hero.jpg) | # Tesi H2<br>The next chapter in hub-center steering.<br>[Discover Tesi H2](/it/it/tesi-h2) |',
  },
  {
    id: 'title',
    name: 'Title',
    category: 'layout',
    what: 'A section heading, used to introduce the content that follows it (e.g. "Models", "Technical Data").',
    how: 'Type a heading and, optionally, a short "pretitle" line above it. There is also a "line" variant that draws an animated vertical line next to the heading as the visitor scrolls past it.',
    when: 'Use above any section that needs its own heading — most pages use several Title blocks to break up the page.',
    fields: [
      ['Pretitle', 'Optional small label above the heading, e.g. "OUR HERITAGE".'],
      ['Heading', 'The section title.'],
    ],
    snippet: '| Title |  |\n|---|---|\n| Our Heritage |  |\n| ## Built in Rimini |  |',
  },
  {
    id: 'text',
    name: 'Text',
    category: 'layout',
    what: 'Plain rich-text content — paragraphs, links, and buttons — with no special layout of its own.',
    how: 'Whatever you type renders close to how you typed it: headings become styled headings, a bold sentence on its own becomes a styled pull-quote, and any linked "button" text becomes a real button.',
    when: 'Use for straightforward copy that doesn\'t need an image alongside it (for that, use Text with Image).',
    fields: [
      ['Body copy', 'Any mix of headings, paragraphs, links.'],
    ],
    snippet: '| Text |  |\n|---|---|\n| ## A note from our founders<br>**"Every Bimota is built to be ridden, not just admired."**<br>Read more about our story below. |  |',
  },
  {
    id: 'text-with-image',
    name: 'Text with Image',
    category: 'layout',
    what: 'A two-column section pairing a block of text with one or two images, side by side.',
    how: 'Put your text in one cell and your image(s) in the other. On desktop the images gently shift position as the visitor scrolls, creating a subtle parallax effect; on mobile they simply stack.',
    when: 'Use for storytelling sections — brand history, craftsmanship, behind-the-scenes content.',
    fields: [
      ['Text column', 'Heading + paragraph(s), optionally a link/button.'],
      ['Image column', 'One or two images.'],
    ],
    snippet: '| Text with Image |  |\n|---|---|\n| ## Built in Rimini<br>Every Bimota is hand-assembled in our Rimini workshop, continuing 50 years of craftsmanship. | ![Workshop photo](/media/workshop.jpg) |',
  },
  {
    id: 'columns',
    name: 'Columns',
    category: 'layout',
    what: 'A flexible layout block that arranges content into 2, 3, or 4 side-by-side columns.',
    how: 'The number of columns is simply however many cells you put in the row. Optional variants change the look: "grid" and "gallery" change spacing, "download" adds a top border (for download-link lists), and a "ratio-X-Y" class controls relative column widths (e.g. a wide text column next to a narrower image column).',
    when: 'Use for comparisons, download lists, or any content that needs simple side-by-side columns without full card styling.',
    fields: [
      ['Column 1..N', 'Each cell in the row becomes one column. Can hold text, images, or both.'],
    ],
    snippet: '| Columns |  |\n|---|---|\n| ### Spec sheet | ### Owner\'s manual | ### Warranty terms |',
  },
  {
    id: 'cards',
    name: 'Cards',
    category: 'layout',
    what: 'A responsive grid of image + heading + text cards — the classic "feature grid" or "model overview" layout.',
    how: 'Each row you add becomes one card. Whichever cell contains only an image becomes the card\'s image; the other cell becomes its body text. The block automatically arranges all cards into a responsive grid.',
    when: 'Use for model overviews, feature highlights, or any "pick one of these" grid of items.',
    fields: [
      ['Card image', 'One image per card.'],
      ['Card body', 'Heading + short text per card.'],
    ],
    snippet: '| Cards |  |\n|---|---|\n| ![DB Model](/media/db-model.jpg) | ### DB Series<br>Classic Bimota lines, modern engineering. |\n| ![Tesi Model](/media/tesi-model.jpg) | ### Tesi Series<br>Hub-center steering, reimagined. |',
  },
  {
    id: 'teaser',
    name: 'Teaser',
    category: 'layout',
    what: 'Very similar to Cards — an image + heading + text item — but styled more compactly, with a smaller heading, for teaser-style callouts rather than a full feature grid.',
    how: 'Same authoring pattern as Cards: one image cell + one text cell per row. The block gives every heading a consistent, slightly smaller style than Cards uses.',
    when: 'Use for secondary callouts (e.g. "related content") where Cards would feel too heavy.',
    fields: [
      ['Teaser image', 'One image per item.'],
      ['Teaser body', 'Heading + short text per item.'],
    ],
    snippet: '| Teaser |  |\n|---|---|\n| ![Owners club photo](/media/club.jpg) | #### Join the Owners Club<br>Exclusive events for Bimota owners. |',
  },
  {
    id: 'news-stories',
    name: 'News / Stories',
    category: 'layout',
    what: 'A card-style list of news items or stories, visually similar to Cards but with its own heading size, purpose-built for news feeds.',
    how: 'Same row-based authoring as Cards: an image cell plus a text cell per news item.',
    when: 'Use on a News/Press page, or a "Latest news" section on the homepage.',
    fields: [
      ['Story image', 'One image per story.'],
      ['Story body', 'Heading + short summary per story.'],
    ],
    snippet: '| News / Stories |  |\n|---|---|\n| ![WorldSBK photo](/media/wsbk.jpg) | ##### Bimota returns to WorldSBK<br>A new chapter for the brand on track. |',
  },
  {
    id: 'feature',
    name: 'Feature',
    category: 'layout',
    what: 'A slide-based feature callout: several "slides" that fade between one another, with small navigation dots the visitor can click.',
    how: 'Each row becomes one slide. The block automatically fades between slides and builds the numbered navigation dots — you don\'t configure the timing or dots yourself.',
    when: 'Use to highlight two or three related features/benefits within a page without needing a full carousel.',
    fields: [
      ['Slide content', 'One row per slide — image and/or text.'],
    ],
    snippet: '| Feature |  |\n|---|---|\n| ![Feature 1](/media/f1.jpg) | ### Lightweight chassis |\n| ![Feature 2](/media/f2.jpg) | ### Handcrafted finish |',
  },
  {
    id: 'highlight',
    name: 'Highlight',
    category: 'layout',
    what: 'A full-width image slider where each image scales/zooms subtly as it comes into view.',
    how: 'Add one image per slide. As the visitor scrolls the block into view, each image animates in with a gentle scale effect; the aspect ratio adapts automatically between mobile and desktop.',
    when: 'Use for a striking, editorial-style image showcase (e.g. a photo essay of a motorcycle in detail).',
    fields: [
      ['Slide image', 'One large image per slide.'],
    ],
    snippet: '| Highlight |  |\n|---|---|\n| ![Detail 1](/media/detail1.jpg) |  |\n| ![Detail 2](/media/detail2.jpg) |  |',
  },
  {
    id: 'gallery',
    name: 'Gallery',
    category: 'layout',
    what: 'A scroll-driven image gallery: images reveal/animate in as the visitor scrolls past them.',
    how: 'Add one image per row. On larger screens, the block tracks how much of each image is visible and animates it accordingly as the visitor scrolls; on very small screens the animation is skipped for performance.',
    when: 'Use for photo galleries — event coverage, workshop tours, model detail shots.',
    fields: [
      ['Image', 'One image per row, in display order.'],
    ],
    snippet: '| Gallery |  |\n|---|---|\n| ![Photo 1](/media/g1.jpg) |  |\n| ![Photo 2](/media/g2.jpg) |  |',
  },
  {
    id: 'carousel',
    name: 'Carousel',
    category: 'layout',
    what: 'A horizontally swipeable set of slides (touch/swipe on mobile, click-through on desktop).',
    how: 'Each row is one slide. The block handles swipe gestures and the sliding transition itself — you only provide the slide content.',
    when: 'Use where visitors should browse several items side-by-side, like a set of accessories or a photo set from an event.',
    fields: [
      ['Slide content', 'One row per slide — usually an image plus a short caption.'],
    ],
    snippet: '| Carousel |  |\n|---|---|\n| ![Slide 1](/media/s1.jpg) | Caption for slide 1 |\n| ![Slide 2](/media/s2.jpg) | Caption for slide 2 |',
  },
  {
    id: 'vehicle-selector',
    name: 'Vehicle Selector',
    category: 'product',
    what: 'A tabbed model picker: a row of clickable model names, each showing its own image and description.',
    how: 'Each row becomes one tab. The heading in that row becomes the clickable tab label; the rest of the row (image, description) is what displays when that tab is active. The block builds the tab navigation and image/description panels itself.',
    when: 'Use on a "Models" overview page where visitors compare several motorcycles.',
    fields: [
      ['Tab heading', 'Becomes the clickable tab label (removed from the visible body text).'],
      ['Tab image', 'Shown when that tab is active.'],
      ['Tab description', 'Shown alongside the image when that tab is active.'],
    ],
    snippet: '| Vehicle Selector |  |\n|---|---|\n| ### Tesi H2<br>![Tesi H2](/media/tesih2.jpg)<br>Supercharged hub-center steering. |  |\n| ### KB4<br>![KB4](/media/kb4.jpg)<br>Naked, aggressive, road-focused. |  |',
  },
  {
    id: 'specification',
    name: 'Specification',
    category: 'product',
    what: 'A stats-style spec section, pairing bold stat values (e.g. "197 hp") with their labels (e.g. "Power"), next to supporting images.',
    how: 'Write each stat as a short paragraph with the value in **bold** — the block detects bold text and styles it as the big stat number, with the rest of the paragraph becoming the label underneath.',
    when: 'Use for a punchy, visual specs section (as opposed to a plain data table — see Specification Table below).',
    fields: [
      ['Stat paragraphs', 'One paragraph per stat, value in **bold**.'],
      ['Images', 'Supporting images shown alongside the stats.'],
    ],
    snippet: '| Specification |  |\n|---|---|\n| **197 hp**<br>Power<br>**187 kg**<br>Dry weight | ![Tesi H2](/media/tesih2-spec.jpg) |',
  },
  {
    id: 'specification-table',
    name: 'Specification Table',
    category: 'product',
    what: 'A categorized technical data table — the classic "full spec sheet" (engine, dimensions, brakes, etc.), grouped under category headings.',
    how: 'The first row is the table title. After that, whenever the first cell of a row has text, it starts a new category group; rows after it (with an empty first cell) are that category\'s label/value pairs.',
    when: 'Use on a model page\'s full technical-specifications section.',
    fields: [
      ['Title row', 'Heading for the whole table.'],
      ['Category cell', 'Starts a new group, e.g. "Engine".'],
      ['Label / Value cells', 'One spec per row, e.g. "Power" / "197 hp".'],
    ],
    snippet: '| Specification Table |  |\n|---|---|\n| ### Tesi H2 Specifications |  |\n| Engine |  |\n|  | Power | 197 hp |\n|  | Displacement | 998 cc |\n| Chassis |  |\n|  | Weight | 187 kg (dry) |',
  },
  {
    id: 'table',
    name: 'Table',
    category: 'product',
    what: 'A plain, simple HTML data table — no categories, no special stat styling, just rows and columns.',
    how: 'Every row/cell you enter becomes a table row/cell, rendered as an ordinary table.',
    when: 'Use for simple tabular content that doesn\'t need Specification Table\'s grouping (e.g. a size/fit chart).',
    fields: [
      ['Rows/cells', 'Whatever you type, one table cell per authoring cell.'],
    ],
    snippet: '| Table |  |\n|---|---|\n| Size | Height |\n| S | 165–172 cm |\n| M | 172–180 cm |',
  },
  {
    id: 'image',
    name: 'Image',
    category: 'layout',
    what: 'A standalone responsive image (or two images side by side).',
    how: 'Drop in one image for a normal full-width image, or two side by side for an automatic "wide row" pairing. A "sticky" variant makes the image stick in place briefly while the visitor scrolls past it.',
    when: 'Use for a simple image with no text needed, where Hero or Text with Image would be overkill.',
    fields: [
      ['Image', 'One image, or two for the side-by-side variant.'],
    ],
    snippet: '| Image |  |\n|---|---|\n| ![Workshop detail](/media/workshop-detail.jpg) |  |',
  },
  {
    id: 'cta-buttons',
    name: 'CTA Buttons',
    category: 'interactive',
    what: 'One or more call-to-action buttons grouped together, e.g. "Book a test ride" + "Find a dealer".',
    how: 'Every link you write becomes a styled button automatically. Add a single trailing "+" to a link\'s text to make it open in a new tab (with an automatic, screen-reader-only "opens in a new tab" notice); use "++" to also show that notice visibly.',
    when: 'Use wherever you need one or two prominent action buttons together — end of a section, end of a page.',
    fields: [
      ['Button links', 'One or more links; trailing + / ++ controls new-tab behavior.'],
    ],
    snippet: '| CTA Buttons |  |\n|---|---|\n| [Book a test ride](/it/it/test-ride) [Find a dealer+](/it/it/dealers) |  |',
  },
  {
    id: 'country-selector',
    name: 'Country Selector',
    category: 'interactive',
    what: 'The locale picker that lets visitors switch between countries/languages (e.g. Italy/Italian → US/English).',
    how: 'It reads its list of countries/regions from a shared data sheet (/countries.json) — you don\'t type countries into the page yourself. When a visitor picks a new country, it tries to send them to the exact same page under the new locale prefix; if that page doesn\'t exist yet, it falls back to that locale\'s homepage instead of a broken link.',
    when: 'Placed once, typically in the header — not something you add to every page individually.',
    fields: [
      ['(data-driven)', 'No per-page fields — content comes from /countries.json. Ask a developer to add a new market there.'],
    ],
    snippet: '| Country Selector | countries |\n|---|---|',
  },
  {
    id: 'dealer-locator',
    name: 'Dealer Locator',
    category: 'interactive',
    what: 'An embedded map widget that lets visitors search for a nearby dealer.',
    how: 'The widget\'s working language is detected automatically from the page\'s URL (e.g. a page under /it/it/ shows the locator in Italian, /de/de/ in German). You don\'t configure the language yourself.',
    when: 'Use on a "Find a dealer" page. One instance per locale folder, matching that locale\'s language.',
    fields: [
      ['(configuration-driven)', 'No per-page authoring fields — language and region come from the page URL.'],
    ],
    snippet: '| Dealer Locator |  |\n|---|---|',
  },
  {
    id: 'woosmapdealers',
    name: 'Woosmap Dealers',
    category: 'interactive',
    what: 'A more advanced dealer/store locator, powered by the WoosMap service, with automatic filtering by world region (Europe, Americas, Asia, Africa, Oceania).',
    how: 'Same idea as Dealer Locator, but backed by WoosMap\'s data and store search, and aware of broad world regions so results can be filtered/grouped sensibly across a large dealer network.',
    when: 'Use where a fuller-featured dealer search experience is needed than the basic Dealer Locator provides.',
    fields: [
      ['(configuration-driven)', 'No per-page authoring fields.'],
    ],
    snippet: '| Woosmap Dealers |  |\n|---|---|',
  },
  {
    id: 'fragment',
    name: 'Fragment',
    category: 'interactive',
    what: 'Pulls in another page\'s content and drops it into the current page — a way to reuse the same content in multiple places.',
    how: 'You give it the path to another page (e.g. a page you maintain just to hold a promo banner). At render time, that page\'s content is fetched and inserted here, fully rendered blocks and all.',
    when: 'Use for anything repeated across many pages: promo banners, legal notices, shared callouts. Edit the source page once; every page using the Fragment updates automatically.',
    fields: [
      ['Path', 'The path to the page whose content should be included here.'],
    ],
    snippet: '| Fragment |  |\n|---|---|\n| /fragments/promo-banner |  |',
  },
  {
    id: 'form',
    name: 'Form',
    category: 'interactive',
    what: 'A configurable form (e.g. contact or lead-generation forms), built from field definitions kept in a separate data sheet rather than typed directly into the page.',
    how: 'You link the block to a form-definition sheet; that sheet lists each field\'s type, label, and whether it\'s required, plus where submissions should be sent. The block builds the actual HTML form, labels, and validation/error messages from that sheet.',
    when: 'Use for contact forms, test-ride requests, newsletter sign-ups — anywhere you need visitor input.',
    fields: [
      ['Form sheet link', 'Path to the linked form-definition document.'],
    ],
    snippet: '| Form |  |\n|---|---|\n| /forms/contact-us |  |',
  },
  {
    id: 'header',
    name: 'Header',
    category: 'site',
    what: 'The site-wide navigation bar shown at the top of every page (logo, menu, country selector).',
    how: 'It isn\'t placed by hand on individual pages — it\'s sourced automatically from a shared "/nav" fragment maintained once for the whole site.',
    when: 'You generally won\'t add this yourself; edit the shared nav content instead, and every page updates.',
    fields: [
      ['(shared content)', 'Maintained in the site\'s shared /nav document, not per-page.'],
    ],
    snippet: '<!-- Not authored per-page — edit the shared /nav document instead. -->',
  },
  {
    id: 'footer',
    name: 'Footer',
    category: 'site',
    what: 'The site-wide footer shown at the bottom of every page (links, legal text, copyright year).',
    how: 'Sourced automatically from a shared "/footer" fragment. A "{year}" token in the footer text is automatically replaced with the current year, so you never need to update the copyright year by hand.',
    when: 'Edit the shared footer content, not individual pages.',
    fields: [
      ['(shared content)', 'Maintained in the site\'s shared /footer document, not per-page.'],
    ],
    snippet: '<!-- Not authored per-page — edit the shared /footer document instead. Use {year} for an auto-updating copyright year. -->',
  },
  {
    id: 'error-page',
    name: 'Error Page',
    category: 'site',
    what: 'The content shown on a 404 / page-not-found state.',
    how: 'Mostly plain content, with one automatic behavior: any "home" link on the page is automatically pointed at the correct site root, so it still works correctly across every locale folder.',
    when: 'One per site (or per locale, if translated); not something you add to regular pages.',
    fields: [
      ['Message + home link', 'Whatever explanatory text you want, plus a link back home.'],
    ],
    snippet: '| Text |  |\n|---|---|\n| ## Page not found<br>[Back to home](/) |  |',
  },
];
